name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev

    - name: Build Google Test
      run: |
        cd /usr/src/gtest
        sudo mkdir -p build
        cd build
        sudo cmake ..
        sudo make
        sudo cp lib/*.a /usr/lib

    - name: Make scripts executable
      run: |
        chmod +x build.sh
        chmod +x test.sh

    - name: Build tests
      run: ./build.sh test

    - name: Run tests
      run: ./test

    - name: Build application (optional)
      run: ./build.sh