name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install build essentials
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Make scripts executable
      run: |
        chmod +x build.sh
        chmod +x test.sh

    - name: Build application
      run: |
        sed -i 's/gcc -o ascii85 test.c/g++ -o ascii85 main.cpp/' build.sh
        ./build.sh

    - name: Run basic test
      run: |
        echo "Test input" | ./ascii85 | ./ascii85 -d | grep "Test input"
        echo "Hello World" | ./ascii85 -e | ./ascii85 -d | grep "Hello World"